(source "marmalade" "https://marmalade-repo.org/packages/")
(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "cedet-git")
(depends-on "company")
(depends-on "company-cmake")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "gradle-mode")
(depends-on "groovy-mode")
(depends-on "helm")
(depends-on "helm-git")
(depends-on "helm-helm-commands")
(depends-on "helm-mode-manager")
(depends-on "helm-package")
(depends-on "helm-projectile")
(depends-on "helm-swoop")
(depends-on "lua-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "yasnippet")