(source "marmalade" "https://marmalade-repo.org/packages/")
(source gnu)
(source melpa)

(depends-on "company")
(depends-on "company-cmake")
(depends-on "gradle-mode")
(depends-on "helm")
(depends-on "helm-git")
(depends-on "helm-helm-commands")
(depends-on "helm-mode-manager")
(depends-on "helm-package")
(depends-on "helm-swoop")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nlinum")
(depends-on "pallet")